In [2]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pylab as plt
import scipy as sp
import scipy.stats as stats

In [ ]:
"""
표준화 중에서도 모집단이 
'정규분포 (normal distribution, Gaussian distribution)을 따르는 경우 
평균이 0, 표준편차는 1 인 표준정규분포(standard normal distribution)로 
표준화 하는 방법을 많이 사용

z = (X-mu)/σ
"""


In [39]:
np.random.seed(0)
data = np.random.randint(30, size=(6, 5))
data

array([[12, 15, 21,  0,  3],
       [27,  3,  7,  9, 19],
       [21, 18,  4, 23,  6],
       [24, 24, 12, 26,  1],
       [ 6,  7, 23, 14, 24],
       [17,  5, 25, 13,  8]])

In [30]:
# numpy를 이용한 표준화 : z = (x-mean())/std()
def standard(x):
    stand = (x - x.mean(axis=0))/x.std(axis=0)
    return stand

stand = standard(data)
print(stand)
# check mean=0 and std=1
print(stand.mean(axis=0))
print(stand.std(axis=0))

[[-0.81572007  0.39620291  0.69987892 -1.641612   -0.84969618]
 [ 1.28184583 -1.18860872 -1.02923371 -0.59870555  1.04729994]
 [ 0.44281947  0.79240582 -1.39975785  1.02359337 -0.49400941]
 [ 0.86233265  1.58481163 -0.41169348  1.37122885 -1.0868207 ]
 [-1.65474644 -0.66033818  0.94689502 -0.01931308  1.64011123]
 [-0.11653144 -0.92447345  1.19391111 -0.13519158 -0.25688489]]
[  1.50342701e-16   5.55111512e-17  -1.48029737e-16   8.78926561e-17
   4.62592927e-17]
[ 1.  1.  1.  1.  1.]


In [33]:
# scipy.stats를 이용한 표준화 : stats.zscore()
stand = stats.zscore(data)
print(stand)
# check mean=0 and std=1
print(stand.mean(axis=0))
print(stand.std(axis=0))

[[-0.81572007  0.39620291  0.69987892 -1.641612   -0.84969618]
 [ 1.28184583 -1.18860872 -1.02923371 -0.59870555  1.04729994]
 [ 0.44281947  0.79240582 -1.39975785  1.02359337 -0.49400941]
 [ 0.86233265  1.58481163 -0.41169348  1.37122885 -1.0868207 ]
 [-1.65474644 -0.66033818  0.94689502 -0.01931308  1.64011123]
 [-0.11653144 -0.92447345  1.19391111 -0.13519158 -0.25688489]]
[  1.50342701e-16   5.55111512e-17  -1.48029737e-16   8.78926561e-17
   4.62592927e-17]
[ 1.  1.  1.  1.  1.]


In [42]:
# sklearn.preprocessing 을 이용한 표준화 
# StandardScaler().fit_transform()
from sklearn.preprocessing import StandardScaler
stand = StandardScaler().fit_transform(data)
print(stand)
# check mean=0 and std=1
print(stand.mean(axis=0))
print(stand.std(axis=0))

[[-0.81572007  0.39620291  0.69987892 -1.641612   -0.84969618]
 [ 1.28184583 -1.18860872 -1.02923371 -0.59870555  1.04729994]
 [ 0.44281947  0.79240582 -1.39975785  1.02359337 -0.49400941]
 [ 0.86233265  1.58481163 -0.41169348  1.37122885 -1.0868207 ]
 [-1.65474644 -0.66033818  0.94689502 -0.01931308  1.64011123]
 [-0.11653144 -0.92447345  1.19391111 -0.13519158 -0.25688489]]
[  1.50342701e-16   5.55111512e-17  -1.48029737e-16   8.78926561e-17
   4.62592927e-17]
[ 1.  1.  1.  1.  1.]


C:\Users\acorn\Anaconda3\lib\site-packages\sklearn\utils\validation.py:429: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, _DataConversionWarning)
