In [2]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pylab as plt
import scipy as sp
import scipy.stats as stats
from sklearn.preprocessing import *

In [ ]:
"""
최소값(Min)과 최대값(Max)을 사용해서 '0~1' 사이의 범위(range)로 
데이터를 표준화해주는 '0~1 변환'

보통 인공신경망, 딥러닝 할 때 변수들을 '0~1' 범위로 변환해서 사용


sklearn.preprocessing.MinMaxScaler() method
sklearn.preprocessing.minmax_scale()
"""

In [15]:
# making data array
np.random.seed(10)
X = np.random.randint(-10, 11, 9).reshape(3, 3)
X


array([[ -1,  -6,   5],
       [-10,   7,   6],
       [  7,  -2,  -1]])

In [16]:
# (1) 최소, 최대값을 구해서 '0~1' 범위로 변환
# (x-min)/(max-min)
print(X.min(axis=0))
print(X.max(axis=0))

def minmax(x):
    x_minmax = (x - x.min(axis=0))/(x.max(axis=0)-x.min(axis=0))
    return x_minmax

minmax(X)

[-10  -6  -1]
[7 7 6]


array([[ 0.52941176,  0.        ,  0.85714286],
       [ 0.        ,  1.        ,  1.        ],
       [ 1.        ,  0.30769231,  0.        ]])

In [51]:
# (2) sklearn.preprocessing.MinMaxScaler()를 사용한 
#     최소.최대 '0~1' 범위 변환

# 1. training
min_max_scaler = MinMaxScaler()
x_train = min_max_scaler.fit_transform(X)
print(x_train)


# making new test data
x1 = np.array([[9, -10, 1],
              [5, -5, 3],
              [1, 0, 5]])

# 훈련 된 것을 기반으로 새로운 데이터 1~0 범위 변환
x1_test = min_max_scaler.transform(X1)
print(x1_test)

[[ 0.52941176  0.          0.85714286]
 [ 0.          1.          1.        ]
 [ 1.          0.30769231  0.        ]]
[[ 1.11764706 -0.30769231  0.28571429]
 [ 0.88235294  0.07692308  0.57142857]
 [ 0.64705882  0.46153846  0.85714286]]


C:\Users\acorn\Anaconda3\lib\site-packages\sklearn\utils\validation.py:429: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, _DataConversionWarning)


In [50]:
# (3) sklearn.preprocessing.minmax_scale()를 
#     사용한 최소.최대 '0~1' 범위 변환

# scaling X  to min~max 0~1 range
x_minmax = minmax_scale(X, axis=0)
x_minmax

C:\Users\acorn\Anaconda3\lib\site-packages\sklearn\utils\validation.py:429: DataConversionWarning: Data with input dtype int32 was converted to float64.
  warnings.warn(msg, _DataConversionWarning)


array([[ 0.52941176,  0.        ,  0.85714286],
       [ 0.        ,  1.        ,  1.        ],
       [ 1.        ,  0.30769231,  0.        ]])