In [1]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pylab as plt
import scipy as sp
import scipy.stats as stats
from sklearn.preprocessing import *

In [ ]:
"""
sklearn.preprocessing.Binarizer()를 사용해서 연속형 변수를 
특정 기준값 이하(equal or less the threshold)이면 '0', 
특정 기준값 초과(above the threshold)이면 '1'
두 개의 값만을 가지는 변수로 변환

확률변수 X가 binomial distribution을 따를 경우 '0' 또는 '1'의 값만을
가지는 이항변수화가 필요.

범주형 자료에 대한 회귀분석, 연관성 분석, text mining 시 
'0'과 '1'의 값을 가지는 dummy variable를 만들어서 분석하기도 한다.


"""

In [2]:
# making test data
np.random.seed(0)
X = np.random.randint(-10, 10, 9).reshape(3, 3)
X

array([[  2,   5, -10],
       [ -7,  -7,  -3],
       [ -1,   9,   8]])

In [14]:
# (1) sklearn.preprocessing.Binarizer() method를 사용한 이항변수화
# threshold = 0.0 : defalut 기준선. 0 보다 크면 1, 0 이하면 0
print(X)
print(Binarizer(threshold=0.0).fit_transform(X))
print(Binarizer(threshold=5.0).transform(X))

[[  2   5 -10]
 [ -7  -7  -3]
 [ -1   9   8]]
[[1 1 0]
 [0 0 0]
 [0 1 1]]
[[0 0 0]
 [0 0 0]
 [0 1 1]]


In [16]:
# sklearn.preprocessing.binarize() 함수를 사용한 이항변수화
print(binarize(X)) # threshold=0.0 default

print(binarize(X, threshold=-3.0))

[[1 1 0]
 [0 0 0]
 [0 1 1]]
[[1 1 0]
 [0 0 0]
 [1 1 1]]


In [17]:
# copy=False로 설정하면 original data 자체가 이항변수화된 값으로 바뀜
print(binarize(X, copy=False))
print(X)

[[1 1 0]
 [0 0 0]
 [0 1 1]]
[[1 1 0]
 [0 0 0]
 [0 1 1]]
