In [7]:
import numpy as np
import pandas as pd
import scipy as sp
import scipy.stats as stats
from sklearn.preprocessing import *
import matplotlib as mpl
import matplotlib.pylab as plt

In [8]:
l = [[x for x in range(1, 6)], [x for x in range(6, 11)]]
a = np.array(l)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
# float 형태로 array
b = np.asfarray(l)
b

array([[  1.,   2.,   3.,   4.,   5.],
       [  6.,   7.,   8.,   9.,  10.]])

In [19]:
e = [1, 2, 3, np.nan, 4]
print(np.array(e))

# 배열값이 무한대거나 nan값이면 error
np.asarray_chkfinite(e)

[  1.   2.   3.  nan   4.]


ValueError: array must not contain infs or NaNs

In [20]:
# 단위행렬
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [23]:
# 1행렬
np.ones(shape=(3, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [28]:
# 0행렬
np.zeros((3, 2, 2))

array([[[ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.]]])

In [30]:
np.empty((3, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])