In [1]:
import numpy as np

In [11]:
a = np.array([1, 2, 3, 4])
print(a)
print(a.shape)

[1 2 3 4]
(4,)


In [18]:
a1 = a[np.newaxis]
print(a1)
print(a1.shape)

[[1 2 3 4]]
(1, 4)


In [19]:
a2 = a1[np.newaxis]
print(a2)
print(a2.shape)

[[[1 2 3 4]]]
(1, 1, 4)


In [20]:
a3 = a2[np.newaxis]
print(a3)
print(a3.shape)

[[[[1 2 3 4]]]]
(1, 1, 1, 4)


In [21]:
b1 = a[:, np.newaxis]
print(b1)
print(b1.shape)

[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [42]:
b2 = b1[:, :, np.newaxis]
print(b2)
print(b2.shape)

[[[1]]

 [[2]]

 [[3]]

 [[4]]]
(4, 1, 1)


In [44]:
c = np.arange(12).reshape(3, 4)
print(c)
print(c.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [50]:
c1 = c[:, :, np.newaxis]
print(c1)
print(c1.shape)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]]
(3, 4, 1)


In [51]:
c2 = c[:, np.newaxis, :]
print(c2)
print(c2.shape)

[[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]]
(3, 1, 4)


In [53]:
a = np.array([0, 1, 2, 3])
print(a)
print(a.shape)

[0 1 2 3]
(4,)


In [54]:
a1 = np.tile(a, 2)
print(a1)
print(a1.shape)

[0 1 2 3 0 1 2 3]
(8,)


In [58]:
a2 = np.tile(a, reps=(2, 2))
print(a2)
print(a2.shape)

[[0 1 2 3 0 1 2 3]
 [0 1 2 3 0 1 2 3]]
(2, 8)


In [59]:
a3 = np.tile(a, reps=(3, 2, 2))
print(a3)
print(a3.shape)

[[[0 1 2 3 0 1 2 3]
  [0 1 2 3 0 1 2 3]]

 [[0 1 2 3 0 1 2 3]
  [0 1 2 3 0 1 2 3]]

 [[0 1 2 3 0 1 2 3]
  [0 1 2 3 0 1 2 3]]]
(3, 2, 8)
