In [1]:
import numpy as np

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
print(a[0])
print(a[[1, 3]])
print(a[3:9])

0
[1 3]
[3 4 5 6 7 8]


In [14]:
# 2 차원 배열
b = np.arange(20).reshape(4, 5)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [20]:
# 1행
print(b[0])
# 1행 3열
print(b[0, 3])
# 2, 4행
print(b[[1, 3]])
# 1 3행, 2 3열
print(b[[0, 2], 1:3])

[0 1 2 3 4]
3
[[ 5  6  7  8  9]
 [15 16 17 18 19]]
[[ 1  2]
 [11 12]]


In [22]:
# 3차원 array
c = np.arange(27).reshape(3, 3, 3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [28]:
# 1면
print(c[0])
# 2면 2행
print(c[1, 1])
# 3면 1행 3열
print(c[2, 0, 2])
# 2면 2 3행, 모든열
print(c[1, [1, 2], :])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[12 13 14]
20
[[12 13 14]
 [15 16 17]]
