In [1]:
import numpy as np

In [2]:
a = np.arange(20).reshape(5, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [7]:
b = np.array(["A", "A", "B", "C", "C"])
b

array(['A', 'A', 'B', 'C', 'C'],
      dtype='<U1')

In [8]:
a[b=="A"]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [9]:
a[b=="C", 0:3]

array([[12, 13, 14],
       [16, 17, 18]])

In [11]:
# A가아닌 행 선택
print(a[b!="A"])
print(a[~(b=="A")])

[[ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [14]:
# A 또는 B 행
print(a[(b=="A") | (b=="B")])
# A와 B가 아닌 행
print(a[(b!="A") & (b!="B")])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]]


In [16]:
# 짝수인 값을 777로 바꾸기
a[a%2==0]=777
print(a)
# 8 이상 15 이하일 경우 10
a[(a>=8) & (a<=15)] = 10
print(a)

[[777   1 777   3]
 [777   5 777   7]
 [777   9 777  11]
 [777  13 777  15]
 [777  17 777  19]]
[[777   1 777   3]
 [777   5 777   7]
 [777  10 777  10]
 [777  10 777  10]
 [777  17 777  19]]
