In [2]:
import numpy as np

In [ ]:
"""
(1) 1개의 배열에 적용하는 Unary Universal Functions (ufuncs)

(2) 2개의 배열에 대해 적용하는 Binary Universal Functions (ufuncs)

"""

In [3]:
# (1-1) 올림 혹은 내림 범용 함수 (round universal functions)

a = np.array([-4.62, -2.19, 0, 1.57, 3.40, 4.06])

a

array([-4.62, -2.19,  0.  ,  1.57,  3.4 ,  4.06])

In [8]:
 # (1-1-1) np.around(a) : 반올림
# 소수 첫째자리에서 반올림
print(np.round(a))
# 둘째 자리에서 반올림
print(np.round(a, 1))

[-5. -2.  0.  2.  3.  4.]
[-4.6 -2.2  0.   1.6  3.4  4.1]


In [10]:
# np.rint(a) : 가장 가까운 정수로 올림 혹은 내림
np.rint(a)

array([-5., -2.,  0.,  2.,  3.,  4.])

In [11]:
# np.fix(a) : '0' 방향으로 가장 가까운 정수로 올림 혹은 내림
np.fix(a)

array([-4., -2.,  0.,  1.,  3.,  4.])

In [15]:
# np.ceil(a) : 올림
np.ceil(a)

array([-4., -2.,  0.,  2.,  4.,  5.])

In [18]:
# np.floor() : 버림
np.floor(a)

array([-5., -3.,  0.,  1.,  3.,  4.])

In [19]:
# np.trunc() : 소수점 미만은 잘라버리고 return
np.trunc(a)

array([-4., -2.,  0.,  1.,  3.,  4.])

In [20]:
a = np.array([1, 2, 3, 4])
b = np.arange(1, 5).reshape(2, 2)
print(a)
print(b)

[1 2 3 4]
[[1 2]
 [3 4]]


In [25]:
# 배열 원소 간 곱 범용 함수 (products universal funcstions) : np.prod()
# 1 dimentional array
print(np.prod(a))

# 2 dimentional array
print(np.prod(b)) # 전체 곱
print(np.prod(b, axis=1)) # 행 곱
print(np.prod(b, axis=0)) # 열 곱

24
24
[ 2 12]
[3 8]


In [34]:
# 배열 원소 간 합치기 범용 함수 (sum universal functions) : np.sum()
# 1 dimentional array
print(np.sum(a))
# keepdims=True : 차원 보존
print(np.sum(a, keepdims=True)) 

# 2 dimentional array
print(np.sum(b)) # 전체 합
print(np.sum(b, axis=1, keepdims=True)) # 행 합
print(np.sum(b, axis=0, keepdims=True)) # 열 합

10
[10]
10
[[3]
 [7]]
[[4 6]]


In [35]:
# NaN 이 포함된 배열 원소 간 곱하기 범용 함수 : np.nanprod()
c = np.array([[1, 2], [3, np.nan]])
c

array([[  1.,   2.],
       [  3.,  nan]])

In [39]:
# nan값을 1로 계산
print(np.nanprod(c)) # 전체
print(np.nanprod(c, axis=1, keepdims=True)) # 행
print(np.nanprod(c, axis=0, keepdims=True)) # 열

6.0
[[ 2.]
 [ 3.]]
[[ 3.  2.]]


In [42]:
# NaN이 포함된 배열 원소 간 더하기 범용 함수 : np.nansum()
# nan값을 0으로 계산
print(np.nansum(c))
print(np.nansum(c, axis=0, keepdims=True))

6.0
[[ 4.  2.]]


In [49]:
# 배열 원소 간 누적 곱하기 범용 함수 : np.cumprod()
print(a)
print(b)

# 1 dimentional array
print(np.cumprod(a))

# 2 dimentional
print(np.cumprod(b, axis=1)) # 행
print(np.cumprod(b, axis=0)) # 열

[1 2 3 4]
[[1 2]
 [3 4]]
[ 1  2  6 24]
[[ 1  2]
 [ 3 12]]
[[1 2]
 [3 8]]


In [50]:
# 배열 원소 간 누적 합 구하기 범용 함수 : np.cumsum()
print(a)
print(b)

# 1 dimentional array
print(np.cumsum(a))

# 2 dimentional
print(np.cumsum(b, axis=1)) # 행
print(np.cumsum(b, axis=0)) # 열

[1 2 3 4]
[[1 2]
 [3 4]]
[ 1  3  6 10]
[[1 3]
 [3 7]]
[[1 2]
 [4 6]]


In [57]:
# 배열 원소 간 n차 차분 구하기 : np.diff()
g = np.array([1, 2, 4, 10, 13, 20])
print(g)
# 1차 차분 : [2-1, 4-2, 10-4, 13-10, 20-13]
print(np.diff(g))

# 2차 차분 : [2-1, 6-2, 3-6, 7-3]  
print(np.diff(g, n=2))

[ 1  2  4 10 13 20]
[1 2 6 3 7]
[ 1  4 -3  4]


In [62]:
np.random.seed(0)
h = np.random.randint(1, 10, 9).reshape(3, 3)
print(h)
# 행 1차 차분
print(np.diff(h, axis=1))
# 행 2차 차분
print(np.diff(h, n=2, axis=1))

# 열 2차 차분
print(np.diff(h, n=2, axis=0))

[[6 1 4]
 [4 8 4]
 [6 3 5]]
[[-5  3]
 [ 4 -4]
 [-3  2]]
[[ 8]
 [-8]
 [ 5]]
[[  4 -12   1]]


In [70]:
# 차분 결과를 1차원 배열(1 dimensional array)로 반환해주는 함수 : ediff1d()
# 1차원 배열
print(np.ediff1d(g))
# 2차원 배열
print(h)
print(np.ediff1d(h))

# to_begin, to_end 설정
print(np.ediff1d(h, to_begin=np.array([-100, 99]), to_end=2000))

[1 2 6 3 7]
[[6 1 4]
 [4 8 4]
 [6 3 5]]
[-5  3  0  4 -4  2 -3  2]
[-100   99   -5    3    0    4   -4    2   -3    2 2000]


In [85]:
# 기울기(gradient) 구하기 범용 함수 : np.gradient()
print(g)

# # [(2-1), {(2-1)+(4-2)}/2, {(4-2)+(10-4)}/2, 
# {(10-4)+(13-10)}/2, {(13-10)+(20-13)}/2, (20-13)]
print(np.gradient(g))

# 양 옆에만 2차 차분 : 1 - (1.5 -1) = 0.5,   7 + (7-5) = 9
print(np.gradient(g, edge_order=2))

# [(2-1)/2, {(2-1)+(4-2)}/2*2, {(4-2)+(10-4)}/2*2, 
# {(10-4)+(13-10)}/2*2, {(13-10)+(20-13)}/2*2, (20-13)/2] 
print(np.gradient(g, 2))


[ 1  2  4 10 13 20]
[ 1.   1.5  4.   4.5  5.   7. ]
[ 0.5  1.5  4.   4.5  5.   9. ]
[ 0.5   0.75  2.    2.25  2.5   3.5 ]


In [88]:
h = np.array([[1, 2, 4, 8], [10, 13, 20, 15]])
print(h)
print(np.gradient(h)) # 열 + 행
print(np.gradient(h, axis=0)) # 열
print(np.gradient(h, axis=1)) # 행

[[ 1  2  4  8]
 [10 13 20 15]]
[array([[  9.,  11.,  16.,   7.],
       [  9.,  11.,  16.,   7.]]), array([[ 1. ,  1.5,  3. ,  4. ],
       [ 3. ,  5. ,  1. , -5. ]])]
[[  9.  11.  16.   7.]
 [  9.  11.  16.   7.]]
[[ 1.   1.5  3.   4. ]
 [ 3.   5.   1.  -5. ]]
