In [1]:
import numpy as np

In [ ]:
"""
* 수 처리 함수 : 절대값(absolute value), 제곱근(square root),
              제곱값(square), 정수와 소수점 값(integral and fractional parts)

 

* 부호(sign) 판별 함수 : 1 (positive), 0(zero), -1(negative) 값 반환



"""

In [3]:
# 배열 원소의 절대값 (absolute value) 범용 함수 : np.abs(x), np.fabs(x)

x = np.array([-100, 1, -4, 100])
print(x)
print(np.abs(x))
print(np.fabs(x))

[-100    1   -4  100]
[100   1   4 100]
[ 100.    1.    4.  100.]


In [6]:
# 배열 원소의 제곱근(Square Root) 범용 함수 : np.sqrt()
x = np.array([1, 4, 100])
print(x)
print(np.sqrt(x))
print(x ** 0.5)

[  1   4 100]
[  1.   2.  10.]
[  1.   2.  10.]


In [7]:
# 배열 원소의 제곱값 (square value) 범용 함수 : np.square()
print(x)
print(np.square(x))
print(x**2)

[  1   4 100]
[    1    16 10000]
[    1    16 10000]


In [11]:
# 배열 원소의 정수와 소수점을 구분하여 2개의 배열 반환 : np.modf()
x = np.array([-13.12, 3.1241, np.pi, 0, 1, 12.2556])
print(x)
print(np.modf(x)[0]) # 소수부분
print(np.modf(x)[1]) # 정수부분

[-13.12         3.1241       3.14159265   0.           1.          12.2556    ]
[-0.12        0.1241      0.14159265  0.          0.          0.2556    ]
[-13.   3.   3.   0.   1.  12.]


In [12]:
# 배열 원소의 부호 판별 함수 : np.sign(x)  
# ☞ 1 (positive), 0(zero), -1(negative)
x = np.array([-31, -2.21, 0, 1, 12, 14])
print(x)
print(np.sign(x))

[-31.    -2.21   0.     1.    12.    14.  ]
[-1. -1.  0.  1.  1.  1.]
